/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caltriangulosarchivos;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import libreriacomun.VentanaBaseLista;

/**
 *
 * @author Scrappy Doo Coco
 */
public class CalTriangulosJFrame extends VentanaBaseLista {

    /**
     * Creates new form CalTriangulosJFrame
     */
    public CalTriangulosJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn10.setText("Procesar");
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(btn10)
                .addContainerGap(824, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(504, Short.MAX_VALUE)
                .addComponent(btn10)
                .addGap(90, 90, 90))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        // Establecer el directorio de trabajo como
        // el directorio por defecto
        chooser.setCurrentDirectory(new File("."));
        //Establecer un fichero por defecto
        //abrir la ventana de dialogo
        int resultado = chooser.showOpenDialog(this);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            File f = chooser.getSelectedFile();
            try {
                double [] a = new double[3];
                double per,s,sup;
                BufferedReader br = new BufferedReader(new FileReader(f));
                String linea;
                while ((linea = br.readLine()) != null){
                    a[0] =Double.parseDouble(linea);
                    if((linea=br.readLine())==null){
                        break;
                    }
                    a[1]=Double.parseDouble(linea);
                    if((linea=br.readLine())==null){
                        break;
                    }
                    a[2]=Double.parseDouble(linea);
                    getModelo().addElement("Lado 1 = "+a[0]+" Lado 2 = "+a[1]+" Lado 3 = "+a[2]);
                    ordenar(a);
                    if((a[0]+a[1])>a[2]){
                        per=a[0]+a[1]+a[2];
                        s= per/2;
                        sup= s;
                        for (int i = 0; i < 3; i++) {
                            sup*=(s-a[i]);
                        }
                        sup = Math.sqrt(sup);
                        getModelo().addElement("Perimetro = "+per+"Superficie = "+sup);
                        if(a[0]==a[2]){
                           getModelo().addElement("Es un tringulo equilatero");

                        }
                        else if(a[1]==a[2]){
                            getModelo().addElement(" Es un trianguloisoceles" );
                        }
                        else {
                            getModelo().addElement(" Es un escaleno" );
                        }
                    }
                    else{
                        getModelo().addElement("No es un triangulo" );
                    }
                
                // Bloque de lectura proceso;
                getLista().setModel(getModelo());
                }
            }
            catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Error al abrir el archivo " + f.getName());
            }
        }
    }//GEN-LAST:event_btn10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalTriangulosJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalTriangulosJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalTriangulosJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalTriangulosJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalTriangulosJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn10;
    // End of variables declaration//GEN-END:variables

    private void ordenar(double[] x) {
        int i, j, n=x.length;
        double z;
        for (i=0; i < n; i++) {
            for(j=i+1;j<n;j++){
                if(x[i]>x[j]){
                    z=x[i];
                    x[i]=x[j];
                    x[j]=z;
                }
            }
        }
    }
}
